### ISSUE TITLE
BadValueError, str not converted to Integer(int)

### ISSUE THREAD

**Issue by thymbahutymba** [pyecore/pyecore#133]
Hi all, I'm trying to load a model using aadl2 and instance [meta-models](https://github.com/osate/osate2/blob/master/core/org.osate.aadl2/model) from OSATE but I got the following error:

```
Traceback (most recent call last):
  File "/home/astevanato/aadl_parser/model_parse.py", line 15, in <module>
    sys_conf = r_set.get_resource(URI("/home/astevanato/aadl_parser/cache_multi_core_dual_Instance.aaxl2"))
  File "/home/astevanato/.local/lib/python3.10/site-packages/pyecore/resources/resource.py", line 93, in get_resource
    resource.load(options=options)
  File "/home/astevanato/.local/lib/python3.10/site-packages/pyecore/resources/xmi.py", line 62, in load
    self._decode_eobject(child, modelroot)
  File "/home/astevanato/.local/lib/python3.10/site-packages/pyecore/resources/xmi.py", line 173, in _decode_eobject
    self._decode_eobject(child, eobject)
  File "/home/astevanato/.local/lib/python3.10/site-packages/pyecore/resources/xmi.py", line 157, in _decode_eobject
    self._decode_eattribute_value(eobject, eattribute, value, from_tag)
  File "/home/astevanato/.local/lib/python3.10/site-packages/pyecore/resources/xmi.py", line 145, in _decode_eattribute_value
    eobject.__getattribute__(eattribute._name).append(value)
  File "/home/astevanato/.local/lib/python3.10/site-packages/pyecore/valuecontainer.py", line 264, in append
    self.check(value)
  File "/home/astevanato/.local/lib/python3.10/site-packages/pyecore/valuecontainer.py", line 71, in check
    raise BadValueError(value, etype, feature)
pyecore.valuecontainer.BadValueError: Expected type Integer(int), but got type str with value 0 instead for feature <EAttribute index: <pyecore.ecore.EProxy object at 0x7fbd7407c4c0>> of <EClass name="ComponentInstance">
```

The offending line contains something like `<index>0</index>`

I find out that in xmi.py in the `_decode_node` function the `etype.force_resolve()` is not assigned back to etype. Then, in the if statement when it is checked whether etype is EDataType, node.text is assigned to value without any conversion, which will results in a str. Am I wrong or it should be converted to the etype? If so, how I can fix it?

**Comment by thymbahutymba** [comment]
I just found out in #78 that there were missing the from_string and to_string for aadl2 types, adding the ones from ecore solved the issue.
