### ISSUE TITLE
ValueError: Feature iD does not exists for type EAttribute

### ISSUE THREAD

**Issue by kdheepak** [pyecore/pyecore#14]
Hi,

When I try to run the following 

```bash
pyecoregen -e schema.ecore -o your_output_path
```

I did the following error.

```python
pyecoregen -e schema.ecore -o your_output_path
Traceback (most recent call last):
  File "/Users/$USER/miniconda2/envs/python3-env/bin/pyecoregen", line 11, in <module>
    sys.exit(main())
  File "/Users/$USER/miniconda2/envs/python3-env/lib/python3.6/site-packages/pyecoregen/cli.py", line 12, in main
    generate_from_cli(sys.argv[1:])  # nocover
  File "/Users/$USER/miniconda2/envs/python3-env/lib/python3.6/site-packages/pyecoregen/cli.py", line 40, in generate_from_cli
    model = load_model(parsed_args.ecore_model)
  File "/Users/$USER/miniconda2/envs/python3-env/lib/python3.6/site-packages/pyecoregen/cli.py", line 59, in load_model
    resource = rset.get_resource(pyecore.resources.URI(ecore_model_path))
  File "/Users/$USER/miniconda2/envs/python3-env/lib/python3.6/site-packages/pyecore/resources/resource.py", line 41, in get_resource
    resource.load()
  File "/Users/$USER/miniconda2/envs/python3-env/lib/python3.6/site-packages/pyecore/resources/xmi.py", line 38, in load
    self._decode_eobject(child, modelroot)
  File "/Users/$USER/miniconda2/envs/python3-env/lib/python3.6/site-packages/pyecore/resources/xmi.py", line 134, in _decode_eobject
    self._decode_eobject(child, eobject)
  File "/Users/$USER/miniconda2/envs/python3-env/lib/python3.6/site-packages/pyecore/resources/xmi.py", line 109, in _decode_eobject
    eobject_info = self._decode_node(parent_eobj, current_node)
  File "/Users/$USER/miniconda2/envs/python3-env/lib/python3.6/site-packages/pyecore/resources/xmi.py", line 186, in _decode_node
    feature = self._decode_attribute(eobject, key, value)
  File "/Users/$USER/miniconda2/envs/python3-env/lib/python3.6/site-packages/pyecore/resources/xmi.py", line 215, in _decode_attribute
    .format(att_name, owner.eClass.name))
ValueError: Feature iD does not exists for type EAttribute
```

Any suggestions on how I can go about debugging this?

**Comment by aranega** [comment]
Hi, 

Thanks for the bug report. Actually, it seems that I forgot to code the `iD` feature in the pyecore metamodel.

The modification is in two step, the first one is to enable the feature decoding by adding L.1198 in `pyecore/ecore.py` the missing feature:

```python
EAttribute.iD = EAttribute('iD', EBoolean)
```
And the second step is to enable the code generator to code this information in the `EAttribute` constructor and in the generated code (so in `pyecoregen` and the Acceleo generator also) . This modification fairly easy, but I need to write corresponding tests.

I fix all of this asap!

**Comment by kdheepak** [comment]
Thanks for the quick reply! I made the first change you suggested. I didn't exactly follow what the second change was.

However, on rerunning I no longer get the first error, but I do receive another error. I'm not sure if this is related to the first one. 

```python
pyecoregen -e schema.ecore -o your_output_path
Traceback (most recent call last):
  File "/Users/$USER/miniconda2/envs/python3-env/bin/pyecoregen", line 11, in <module>
    sys.exit(main())
  File "/Users/$USER/miniconda2/envs/python3-env/lib/python3.6/site-packages/pyecoregen/cli.py", line 12, in main
    generate_from_cli(sys.argv[1:])  # nocover
  File "/Users/$USER/miniconda2/envs/python3-env/lib/python3.6/site-packages/pyecoregen/cli.py", line 40, in generate_from_cli
    model = load_model(parsed_args.ecore_model)
  File "/Users/$USER/miniconda2/envs/python3-env/lib/python3.6/site-packages/pyecoregen/cli.py", line 59, in load_model
    resource = rset.get_resource(pyecore.resources.URI(ecore_model_path))
  File "/Users/$USER/miniconda2/envs/python3-env/lib/python3.6/site-packages/pyecore/resources/resource.py", line 41, in get_resource
    resource.load()
  File "/Users/$USER/miniconda2/envs/python3-env/lib/python3.6/site-packages/pyecore/resources/xmi.py", line 39, in load
    self._decode_ereferences()
  File "/Users/$USER/miniconda2/envs/python3-env/lib/python3.6/site-packages/pyecore/resources/xmi.py", line 233, in _decode_ereferences
    .format(value))
ValueError: EObject for ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate is unknown
```

Do you know what might be going on or how I should proceed?

**Comment by aranega** [comment]
Oh, right, it is a missing `EDataType` in the pyecore metamodel... I also forgot to add the `EDate` datatype. The modification is also quite easy (I will add it right after the `iD` feature) in the `pyecore/ecore.py` file:

at the import level:
```python
import datetime
```
then, L.1167:
```python
EDate = EDataType('EDate', datetime)
```
then, L.1297:
```python
Core.register_classifier(EDate)
```
and finally, add `EDate` in `__all__`, L.1308:

```python
..., 'EDate']
```

You surely have a great metamodel to deal with all the missing feature! I'm adding the type right away.

**Comment by aranega** [comment]
I added the missing `iD` feature and `EDate` on the `devrop` branch. I also modified the Acceleo generator to deal with the `iD` feature, you should not be bother with this anymore.

I need to go, but I will adapt the `pyecoregen` generator as soon as I can.

**Comment by kdheepak** [comment]
Thanks for the quick fixes! I seem to have found another object that is unknown.

```python
pyecoregen -e schema.ecore -o your_output_path
Traceback (most recent call last):
  File "/Users/$USER/miniconda2/envs/python3-env/bin/pyecoregen", line 11, in <module>
    sys.exit(main())
  File "/Users/$USER/miniconda2/envs/python3-env/lib/python3.6/site-packages/pyecoregen/cli.py", line 12, in main
    generate_from_cli(sys.argv[1:])  # nocover
  File "/Users/$USER/miniconda2/envs/python3-env/lib/python3.6/site-packages/pyecoregen/cli.py", line 40, in generate_from_cli
    model = load_model(parsed_args.ecore_model)
  File "/Users/$USER/miniconda2/envs/python3-env/lib/python3.6/site-packages/pyecoregen/cli.py", line 59, in load_model
    resource = rset.get_resource(pyecore.resources.URI(ecore_model_path))
  File "/Users/$USER/miniconda2/envs/python3-env/lib/python3.6/site-packages/pyecore/resources/resource.py", line 41, in get_resource
    resource.load()
  File "/Users/$USER/miniconda2/envs/python3-env/lib/python3.6/site-packages/pyecore/resources/xmi.py", line 39, in load
    self._decode_ereferences()
  File "/Users/$USER/miniconda2/envs/python3-env/lib/python3.6/site-packages/pyecore/resources/xmi.py", line 233, in _decode_ereferences
    .format(value))
ValueError: EObject for ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal is unknown
```

**Comment by aranega** [comment]
Arf, you're right, this time, this is the `EBigDecimal` which is missing. I'm really sorry I forgot so much types... I fix this as soon as I come back home!

**Comment by kdheepak** [comment]
No problem! This is a great package btw :)

**Comment by aranega** [comment]
Thanks a lot! I really hope it will be soon 'missing EDataType'-free ;)

So, I finally pushed on `develop` the missing `EBigDecimal`. By the same occasion, I also pushed some other missing basic `EDataType`:

* `EBigDecimal`
* `EBooleanObject`
* `ELongObject`
* `EByte`
* `EByteObject`
* `EByteArray`
* `EChar`
* `ECharacterObject`
* `EShort`
* `EJavaClass`

However, if you use `EByte`, `EByteObject` or `EByteArray`, I'm not sure about the 'serialization' of these `EDataType` at the moment (each `EDataType` instance can express the way they will be serilized and how they need to be deserialized when they are read from the XMI file, I'm not sure yet the best way to handle them).

I hope this time, all the `EDataType` you need are in the pyecore metamodel.

**Comment by aranega** [comment]
I've release a new version of PyEcore on pypi (0.5.11) that adds the missing feature for the `EAttribute` and the missing `EDataTypes`. 
Also, there is a new version of pyecoregen on pypi (0.3.0) which deals with the `iD` feature generation and prevent Python name clashes.

You can update everything using

    $ pip install pyecore pyecoregen -U
