### ISSUE TITLE
Metamodel dynamic extend error

### ISSUE THREAD

**Issue by suntao2012** [pyecore/pyecore#19]
@aranega
I import an python lib which is generated by pyecore, then I want to extend an attribute to one EClass, it added successfully, however, it didn't add to class object actually. I use a simple test cast like this:

```
Python 3.4.3 (default, Nov 17 2016, 01:08:31)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyecore.ecore import *
>>> import cofluent
>>> a = cofluent.TESTCLASS()
>>> dir(a)
['content']
>>> a.content
>>> cofluent.TESTCLASS.eClass.eStructuralFeatures.append(EAttribute('name', EString, default_value='new_name'))
>>> dir(a)
['content', 'name']
>>> a.content
>>> a.name
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'TESTCLASS' object has no attribute 'name'
>>>

```

did I use it in a wrong way or how do I fix this?

**Comment by aranega** [comment]
@suntao2012 As always, you put your finger on the point I didn't document :).

By default, static metamodels (generated metamodel) disable the "dynamic modification" feature for performances purpose. The idea is that, the major part of the time, when you

**Comment by suntao2012** [comment]
@aranega your answer is great. the attribute could be added.
because my requests are always strange. we want to extend our model lib very flexible and dynamic rather than write *.ecore file every time. 

another issue is how do I add a new class dynamically and save to XMI. I tried like following, but some nsPrefix errors occured.

```
Node = EClass('Node')
cofluent.TESTCLASS._staticEClass = False
cofluent.TESTCLASS.eClass.eStructuralFeatures.append(EAttribute('name', EString, default_value='new_name'))
contains_nodes = EReference('nodes', Node, upper=-1, containment=True)
cofluent.TESTCLASS.eClass.eStructuralFeatures.append(contains_nodes)

def save(obj):
	rset = ResourceSet()
	resource = rset.create_resource('TESTCLASS.XMI.2')
	resource.use_uuid = True
	resource.append(obj)
	resource.save()

root = cofluent.TESTCLASS()
root.nodes.append(Node())
print(dir(root))
print(root.nodes)
save(root)
```
the errors like this:
```
['content', 'name', 'nodes']
EOrderedSet([<pyecore.ecore.Node object at 0x7f15684cdd30>])
Traceback (most recent call last):
  File "a.py", line 29, in <module>
    save(root)
  File "a.py", line 21, in save
    resource.save()
  File "/home/suntao/PY3ENV/lib/python3.4/site-packages/pyecore/resources/xmi.py", line 310, in save
    old_root_node = self._go_across(root, serialize_default)
  File "/home/suntao/PY3ENV/lib/python3.4/site-packages/pyecore/resources/xmi.py", line 421, in _go_across
    node.append(self._go_across(child, serialize_default))
  File "/home/suntao/PY3ENV/lib/python3.4/site-packages/pyecore/resources/xmi.py", line 340, in _go_across
    self.register_eobject_epackage(obj)
  File "/home/suntao/PY3ENV/lib/python3.4/site-packages/pyecore/resources/xmi.py", line 292, in register_eobject_epackage
    prefix = epackage.nsPrefix
AttributeError: 'NoneType' object has no attribute 'nsPrefix'
```

does pyecore support this usage? if does, how do I use it correctly?

**Comment by suntao2012** [comment]
@aranega thanks a lot, that helped. : )
