### ISSUE TITLE
Issue with latest version of ordered-set

### ISSUE THREAD

**Issue by larsderidder** [pyecore/pyecore#88]
The ordered-set dependency was updated to 4.0.1 at the 29th of April, which causes the following stacktrace when pyecore is imported:

```
Traceback (most recent call last):
  File "esdl/__init__.py", line 1, in <module>
    from pyecore.resources import global_registry
  File "/lib/python3.7/site-packages/pyecore/resources/__init__.py", line 1, in <module>
    from .resource import ResourceSet, Resource, URI, global_registry, \
  File "/lib/python3.7/site-packages/pyecore/resources/resource.py", line 12, in <module>
    from .. import ecore as Ecore
  File "/lib/python3.7/site-packages/pyecore/ecore.py", line 1039, in <module>
    from .valuecontainer import ECollection, EValue, \
  File "/lib/python3.7/site-packages/pyecore/valuecontainer.py", line 3, in <module>
    from .ordered_set_patch import ordered_set
  File "/lib/python3.7/site-packages/pyecore/ordered_set_patch.py", line 4, in <module>
    is_iterable = ordered_set.is_iterable
AttributeError: module 'ordered_set' has no attribute 'is_iterable'
```

Solution on our side is to pin ordered-set on version 3.1.1, but probably pyecore should either handle the new version or pin the dependency (or both).

**Comment by aranega** [comment]
Hi @larsderidder 

Thanks for the report!
That's strange, I released a new version few days ago that deals with the new dependency and pinne the dep (in the [`setup.py L35`](https://github.com/pyecore/pyecore/blob/285723b98a84d41e9eb18b29efa8706767abe561/setup.py#L35)). 
Are you using version `0.11.6`?

**Comment by larsderidder** [comment]
Hi @aranega,

Oh I see, you are right, we appear to still run on an older version of pyecore. I just updated pyecore and it works like a charm. Thanks!
